apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-rest-api
  namespace: fast-food-ecosystem
spec:
  selector:
    matchLabels:
      app: fast-food-rest-api
  template:
    metadata:
      labels:
        app: fast-food-rest-api
    spec:
      serviceAccountName: secret-manager-service-account
      volumes:
        - name: secret-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gerenciador-secret-credentials
      containers:
        - name: fast-food-rest-api
          image: 975049969291.dkr.ecr.us-east-1.amazonaws.com/gerenciador-pedidos:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-gerenciador-pedidos
                  key: dburl
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-gerenciador-pedidos
                  key: dbuser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-gerenciador-pedidos
                  key: dbpass
            - name: JWT_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: secret-gerenciador-pedidos
                  key: jwtissuer
            - name: PAYMENT_URL
              valueFrom:
                secretKeyRef:
                  name: secret-gerenciador-pedidos
                  key: paymenturl
          volumeMounts:
            - name: secret-volume
              mountPath: /mnt/secrets
              readOnly: true