apiVersion: secrets-store.csi.x-k8s.io/v1alpha1

kind: SecretProviderClass

metadata:

  name: gerenciador-secret-credentials

spec:

  provider: aws
  secretObjects:
  - secretName: secret-gerenciador-pedidos
    type: Opaque
    data: 
    - objectName: DB_USER
      key: dbuser
    - objectName: DB_PASS
      key: dbpass
    - objectName: DATABASE_URL
      key: dburl
    - objectName: JWT_ISSUER_URI
      key: jwtissuer
    - objectName: PAYMENT_URL
      key: paymenturl
  parameters:
    objects: |

        - objectName: "gerenciador-pedidos"
          objectType: "secretsmanager"
          jmesPath: 
              - path: dbuser
                objectAlias: DB_USER

              - path: dbpass
                objectAlias: DB_PASS

              - path: dburl
                objectAlias: DATABASE_URL

              - path: jwtissuer
                objectAlias: JWT_ISSUER_URI     
              - path: paymenturl
                objectAlias: PAYMENT_URL    
          objectType: "secretsmanager"