apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fast-food-rest-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fast-food-rest-api
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
